# Generated by Django 5.2 on 2026-03-21
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greedybear", "0041_sharetoken"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventSource",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64)),
                ("token_hash", models.CharField(db_index=True, max_length=64, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("rate_limit", models.PositiveIntegerField(default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_sources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InjectedEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("queued", "Queued"), ("processed", "Processed"), ("failed", "Failed")],
                        default="queued",
                        max_length=32,
                    ),
                ),
                ("error_text", models.TextField(blank=True, default="")),
                ("observable_value", models.CharField(max_length=256)),
                ("observable_type", models.CharField(choices=[("ip", "Ip"), ("domain", "Domain")], max_length=32)),
                ("payload_json", models.JSONField(default=dict)),
                ("external_event_id", models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="injected_events",
                        to="greedybear.eventsource",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("external_event_id__isnull", False)),
                        fields=("source", "external_event_id"),
                        name="unique_injected_event_external_id_per_source",
                    )
                ],
            },
        ),
    ]
